name: Deploy DV Application

on:
  push:
    branches:
        - origin

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u kaushikred293 -p cnwFri_123 
            - name: Build Docker Image
              run: docker build -t  kaushikred293/diagno-vet-frontend ./frontend/
            - name: Publish Image to docker hub
              run: docker push kaushikred293/diagno-vet-frontend:latest
    deploy:
        needs: build
        runs-on: self-hosted 
        steps:
            - name: Pull image from Docker hub
              run: docker pull kaushikred293/diagno-vet-frontend:latest
            - name: Delete Old Container
              run: docker rm -f frontend-container
            - name: Run Docker Container
              run: docker run -d -p 3000:80 --name frontend-container kaushikred293/diagno-vet-frontend:latest